# vim:ts=2:sts=2:sw=2:et:
---
version: 2
jobs:
  "elixir-1.4":
    docker:
      - image: circleci/elixir:1.4
        environment:
          PGUSER: root
          PGHOST: 127.0.0.1

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: phoenix_mtm_test

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test

workflows:
  version: 2
  build:
    jobs:
      - "elixir-1.4"
